import { createContext, useContext } from 'react';

const TRANSLATIONS = {
  en: {
    nav_dashboard:'Dashboard', nav_inbox:'Inbox', nav_jobs:'Job Search', nav_crm:'CRM', nav_leads:'Leads & Prospecting', nav_prospecting:'Leads & Prospecting', nav_clients:'Network',
    nav_projects:'Projects', nav_tasks:'Tasks', nav_suppliers:'Suppliers', nav_finance:'Finance',
    nav_documents:'Documents', nav_ai:'AI Assistant', nav_automation:'Automation', nav_settings:'Settings',
    grp_workspace:'Workspace', grp_sales:'Sales', grp_delivery:'Delivery', grp_ops:'Operations', grp_intel:'Intelligence',
    search_ph:'Search clients, deals, tasks…',
    save:'Save', cancel:'Cancel', saving:'Saving…', add:'Add', export_csv:'Export CSV',
    filter:'Filter', all:'All', view_all:'View all', sign_out:'Sign out',
    delete_confirm: 'Delete', no_industry:'No industry', no_client:'No client',
    dash_morning:'Good morning', dash_afternoon:'Good afternoon', dash_evening:'Good evening',
    dash_sub:"Here's how {ws} is performing",
    dash_welcome_title:'Welcome to', dash_quick_add:'Quick add',
    dash_welcome_sub:'Start by adding clients, creating deals in the CRM, or adding tasks to track your work.',
    dash_add_client:'Add a client', dash_create_deal:'Create a deal', dash_add_task:'Add a task',
    dash_rev:'Revenue collected', dash_pipeline:'Open pipeline', dash_clients:'Active clients',
    dash_tasks:'Tasks pending', dash_due_today:'{n} due today',
    dash_pipeline_stage:'Pipeline by stage', dash_open_deals:'{n} open deals',
    dash_no_open_deals:'No open deals yet.',
    dash_finance_snap:'Finance snapshot', dash_recent_clients:'Recent clients',
    dash_upcoming:'Upcoming tasks', dash_all_caught:'All caught up!',
    dash_paid_inv:'{n} paid invoices', dash_open_d:'{n} open deals',
    dash_clients_count:'{n} clients',
    crm_sub:'{n} deals · {v} in open pipeline',
    crm_new:'New deal', crm_pipeline:'Pipeline', crm_table:'Table',
    crm_company:'Company', crm_contact:'Contact', crm_industry:'Industry',
    crm_stage:'Stage', crm_value:'Value', crm_prob:'Prob.',
    crm_drop:'Drop here', crm_win_prob:'Win prob.',
    crm_no_deals:'No deals yet. Create your first deal.',
    crm_deal_value:'Deal value',
    cli_sub:'{n} active clients · {mrr} MRR',
    cli_new:'Add client', cli_all:'All clients',
    cli_no_clients:'No clients yet. Add your first client to get started.',
    cli_mrr:'MRR', cli_lifetime:'Lifetime value', cli_active_proj:'Active projects',
    cli_health:'Health', cli_since:'client since',
    cli_email:'Email', cli_call:'Call', cli_comm:'Communication history',
    cli_docs:'Documents', cli_contract:'Contract', cli_active:'Active',
    tasks_sub:'{n} tasks · {p} pending',
    tasks_new:'New task', tasks_no_tasks:'No tasks yet. Add one to get started.',
    tasks_today:'Today', tasks_tomorrow:'Tomorrow', tasks_week:'This week',
    tasks_all:'All', tasks_pending:'Pending', tasks_done:'Done',
    proj_sub:'{n} tasks across {c} clients',
    proj_new:'New task', proj_drop:'Drop tasks here',
    proj_filter:'Filter', proj_subtasks:'{a}/{b} subtasks',
    sup_sub:'{n} suppliers · {v} total spend',
    sup_new:'Add supplier', sup_add_first:'Add first supplier',
    sup_no_sup:'No suppliers yet',
    sup_no_sub:'Add your suppliers to track spend and contact details.',
    sup_cat:'Category', sup_loc:'Location', sup_rating:'Rating',
    sup_status:'Status', sup_spend:'Spend', sup_all:'All suppliers',
    sup_total:'Total suppliers', sup_total_spend:'Total spend', sup_avg_rating:'Avg. rating',
    sup_preferred:'preferred', sup_of5:'out of 5',
    fin_sub:'Revenue, expenses and cash flow.',
    fin_overview:'Overview', fin_entries:'All entries', fin_new:'New entry',
    fin_no_data:'No financial data yet',
    fin_no_sub:'Add invoices and expenses to track your revenue, costs and profit.',
    fin_add_first:'Add first entry',
    fin_rev:'Revenue collected', fin_exp:'Total expenses',
    fin_net:'Net profit', fin_pending_inv:'Pending invoices',
    fin_rev_break:'Revenue breakdown', fin_summary:'Summary',
    fin_recent:'Recent entries',
    fin_label:'Label', fin_type:'Type', fin_client:'Client',
    fin_date:'Date', fin_status:'Status', fin_amount:'Amount',
    fin_invoice:'Invoice', fin_expense:'Expense',
    fin_paid:'Paid', fin_sent:'Sent', fin_draft:'Draft', fin_overdue:'Overdue',
    fin_no_entries:'No entries yet. Add invoices and expenses to get started.',
    fin_total_inv:'Total invoiced', fin_collected:'Collected',
    fin_still_pending:'Still pending', fin_expenses:'Expenses',
    fin_net_profit:'Net profit', fin_positive:'Positive', fin_negative:'Negative',
    fin_invoices:'{n} paid invoices', fin_entries_n:'{n} entries',
    doc_sub:'{n} file{s} · contracts, quotes, invoices and more.',
    doc_new:'Add document', doc_search:'Search documents',
    doc_no_docs:'No documents yet. Add your first file.',
    doc_all:'All files', doc_name:'Name', doc_folder:'Folder',
    doc_size:'Size', doc_modified:'Modified',
    doc_contracts:'Contracts', doc_quotes:'Quotes', doc_invoices:'Invoices',
    doc_certificates:'Certificates', doc_legal:'Legal', doc_brand:'Brand assets',
    pros_sub:'Cold outreach campaigns and prospect tracking.',
    pros_new_camp:'New campaign', pros_new:'New prospect',
    pros_campaigns:'Campaigns', pros_prospects:'Prospects',
    pros_city:'City', pros_stage:'Stage', pros_last:'Last', pros_actions:'Actions',
    pros_no_camp:'No campaigns yet.', pros_no_pros:'No prospects yet.',
    pros_emails:'Emails sent', pros_open:'Open rate', pros_reply:'Reply rate',
    pros_meetings:'Meetings booked', pros_this_month:'this month',
    pros_active:'Active', pros_paused:'Paused',
    pros_across:'{n} campaigns', pros_opened:'{n} opened',
    pros_replies:'{n} replies', pros_sent:'sent',
    pros_ai:'Generate AI outreach', pros_ai_draft:'AI outreach draft',
    pros_for:'Personalized for',
    pros_website:'Website', pros_email:'Email', pros_phone:'Phone',
    pros_linkedin:'LinkedIn', pros_industry:'Industry',
    ai_title:'AI Assistant',
    ai_sub:'Write emails & proposals, generate scripts, analyze leads, summarize meetings and more.',
    ai_ph:'Ask the assistant anything…',
    ai_p1:'Write a follow-up email', ai_p2:'Draft a project proposal',
    ai_p3:'Generate a sales script', ai_p4:'Brainstorm campaign ideas',
    ai_regen:'Regenerate', ai_send_email:'Send email',
    auto_title:'Automation Center',
    auto_sub:'Build workflows that run your busywork.',
    auto_coming:'Coming soon',
    auto_desc:'Automation workflows will let you trigger actions automatically — send emails, create tasks, notify your team — based on events in your CRM.',
    auto_dev:'This feature is in development.',
    set_sub:'Workspace, billing and integrations.',
    set_workspace:'Workspace', set_ws_name:'Workspace name', set_ws_shown:'Shown across the app',
    set_account:'Account', set_plan:'Plan', set_free:'Free',
    set_integrations:'Integrations', set_connected:'Connected', set_connect:'Connect',
    set_language:'Language', set_lang_sub:'Interface language',
    set_tip:'Tip: use the', set_tweaks:'Tweaks', set_tip2:'panel (bottom-right) to change layout and accent color.',
    set_lang_en:'English', set_lang_fr:'Français',
    m_new_client:'New client', m_new_deal:'New deal', m_new_task:'New task',
    m_new_proj:'New project task', m_new_prospect:'New prospect',
    m_new_campaign:'New campaign', m_new_finance:'New entry',
    m_finance_sub:'Invoice or expense',
    m_new_supplier:'New supplier', m_new_doc:'Add document',
    f_company:'Company name', f_contact:'Contact name', f_industry:'Industry',
    f_email:'Email', f_phone:'Phone', f_website:'Website', f_mrr:'MRR (€)',
    f_health:'Health', f_since:'Client since',
    f_value:'Value (€)', f_stage:'Stage', f_owner:'Owner',
    f_title:'Title', f_client:'Client', f_prio:'Priority', f_due:'Due',
    f_col:'Column', f_due_date:'Due date', f_tags:'Tags (comma-separated)',
    f_city:'City', f_linkedin:'LinkedIn', f_active:'Launch as active', f_campaign:'Campaign name',
    f_type:'Type', f_amount:'Amount (€)', f_label:'Label', f_status:'Status', f_date:'Date',
    f_category:'Category', f_location:'Location',
    f_rating:'Rating (0–5)', f_spend:'Annual spend (€)', f_size:'Size',
    f_folder:'Folder', f_filename:'File name',
    f_health_good:'Good', f_health_watch:'Watch', f_health_risk:'At risk',
    stage_new_lead:'New Lead', stage_qualified:'Qualified', stage_proposal:'Proposal Sent',
    stage_negotiation:'Negotiation', stage_won:'Won', stage_lost:'Lost',
    stage_queued:'Queued', stage_contacted:'Contacted', stage_replied:'Replied',
    stage_meeting:'Meeting', stage_converted:'Converted', stage_archived:'Archived',
    ai_setup_title:'Set up your AI assistant', ai_setup_desc:'Add your free Groq API key to enable real AI actions.',
    ai_setup_step1:'Go to console.groq.com and sign up (free, no credit card)',
    ai_setup_step2:'Click "Create API Key" and copy it',
    ai_setup_step3:'Paste it below and click Activate',
    ai_activate:'Activate AI',
    inbox_add_account:'Add another account', inbox_accounts:'Connected accounts',
    inbox_connect_email_ph:'your@email.com', inbox_connect_email_label:'Your email address',
    f_prio_high:'High', f_prio_med:'Medium', f_prio_low:'Low',
    f_today:'Today', f_tomorrow:'Tomorrow', f_week:'This week',
    f_todo:'To Do', f_inprog:'In Progress', f_waiting:'Waiting', f_done:'Completed',
    f_active:'Active', f_paused:'Paused', f_preferred:'Preferred', f_trial:'Trial', f_inactive:'Inactive',
    f_inv:'Invoice', f_exp:'Expense', f_draft2:'Draft', f_sent:'Sent', f_paid:'Paid',
    doc_file_label:'File (optional)', doc_file_ph:'Click to select a file…',
    doc_storage_note:'Requires a "documents" storage bucket in Supabase.',
    doc_uploading:'Uploading…', doc_upload_err:'Upload failed — metadata saved only.',
    jobs_sub:'{n} applications', jobs_new:'New application',
    jobs_total:'Total sent', jobs_pending:'Pending', jobs_no_reply:'no reply',
    jobs_interviews:'Interviews', jobs_offers:'Offers', jobs_rate:'Response rate', jobs_response_rate:'answered',
    jobs_empty_title:'No applications yet', jobs_empty_desc:"Start adding your job applications to track where you've applied.",
    jobs_no_match:'No results', jobs_no_match_desc:'No applications match this filter.',
    jobs_col_company:'Company', jobs_col_position:'Position', jobs_col_location:'Location',
    jobs_col_platform:'Platform', jobs_col_date:'Date', jobs_col_salary:'Salary', jobs_col_status:'Status',
    jobs_salary_min:'Salary min (€)', jobs_salary_max:'Salary max (€)',
    jobs_url:'Job posting URL', jobs_contact:'Contact person', jobs_notes:'Notes',
    jobs_view_offer:'View offer', jobs_search:'Search…',
    job_applied:'Applied', job_interview:'Interview', job_test:'Tech test',
    job_offer:'Offer received', job_rejected:'Rejected', job_withdrawn:'Withdrawn', job_accepted:'Accepted',
    inbox_title:'Inbox', inbox_sub:'Your emails, in one place.',
    inbox_connect:'Connect your inbox', inbox_connect_sub:'Sync your email to see conversations, reply to clients, and manage your business communications.',
    inbox_connect_btn:'Connect', inbox_imap_desc:'Any email provider',
    inbox_privacy_title:'Your emails stay secure', inbox_privacy_desc:'We only read your emails when you ask.',
    inbox_disconnect:'Disconnect', inbox_compose:'Compose',
    inbox_sync_coming:'Real-time sync coming soon', inbox_sync_desc:'This is a preview of your inbox.',
    inbox_folder_inbox:'Inbox', inbox_folder_sent:'Sent', inbox_folder_drafts:'Drafts', inbox_folder_trash:'Trash',
    inbox_empty:'This folder is empty.', inbox_from:'From', inbox_reply:'Reply', inbox_no_selection:'Select an email to read it.',
    ai_no_key:'No API key configured. Set it up on this page.',
    ai_tool_client:'Adding client', ai_tool_deal:'Creating deal', ai_tool_task:'Creating task',
    ai_tool_prospect:'Adding prospect', ai_tool_search:'Searching web', ai_tool_data:'Reading data',
    ai_clear:'New conversation',
    set_ai:'AI Assistant (Groq — free)', set_ai_key:'Groq API key (free)', set_ai_key_ph:'gsk_…',
    set_ai_key_desc:'Get your free key at console.groq.com — no credit card required.',
    set_ai_key_note:'Free tier: 14,400 requests/day. Stored in your browser only.',
    auth_login:'Sign in', auth_register:'Create account',
    auth_email:'Email address', auth_password:'Password',
    auth_name:'Full name', auth_workspace:'Workspace name',
    auth_workspace_ph:'My Agency',
    auth_have:'Already have an account?', auth_no_acc:"Don't have an account?",
    auth_signin:'Sign in', auth_create:'Create one',
    auth_success:'Account created! Signing you in…',
  },
  fr: {
    nav_dashboard:'Tableau de bord', nav_inbox:'Boîte de réception', nav_jobs:'Recherche emploi', nav_crm:'CRM', nav_leads:'Leads & Prospection', nav_prospecting:'Leads & Prospection',
    nav_clients:'Réseaux', nav_projects:'Projets', nav_tasks:'Tâches',
    nav_suppliers:'Fournisseurs', nav_finance:'Finance', nav_documents:'Documents',
    nav_ai:'Assistant IA', nav_automation:'Automatisation', nav_settings:'Paramètres',
    grp_workspace:'Espace de travail', grp_sales:'Ventes', grp_delivery:'Livraison',
    grp_ops:'Opérations', grp_intel:'Intelligence',
    search_ph:'Rechercher clients, deals, tâches…',
    save:'Enregistrer', cancel:'Annuler', saving:'Enregistrement…', add:'Ajouter', export_csv:'Exporter CSV',
    filter:'Filtrer', all:'Tous', view_all:'Voir tout', sign_out:'Se déconnecter',
    delete_confirm:'Supprimer', no_industry:'Pas de secteur', no_client:'Pas de client',
    dash_morning:'Bonjour', dash_afternoon:'Bon après-midi', dash_evening:'Bonsoir',
    dash_sub:'Voici les performances de {ws}',
    dash_welcome_title:'Bienvenue sur', dash_quick_add:'Ajouter',
    dash_welcome_sub:"Commencez par ajouter des clients, créer des deals dans le CRM, ou ajouter des tâches pour suivre votre travail.",
    dash_add_client:'Ajouter un client', dash_create_deal:'Créer un deal', dash_add_task:'Ajouter une tâche',
    dash_rev:'Revenus encaissés', dash_pipeline:'Pipeline ouvert', dash_clients:'Clients actifs',
    dash_tasks:'Tâches en attente', dash_due_today:"{n} à faire aujourd'hui",
    dash_pipeline_stage:'Pipeline par étape', dash_open_deals:'{n} deals ouverts',
    dash_no_open_deals:"Aucun deal ouvert pour l'instant.",
    dash_finance_snap:'Résumé financier', dash_recent_clients:'Clients récents',
    dash_upcoming:'Tâches à venir', dash_all_caught:'Tout est à jour !',
    dash_paid_inv:'{n} factures payées', dash_open_d:'{n} deals ouverts',
    dash_clients_count:'{n} clients',
    crm_sub:'{n} deals · {v} en pipeline ouvert',
    crm_new:'Nouveau deal', crm_pipeline:'Pipeline', crm_table:'Tableau',
    crm_company:'Société', crm_contact:'Contact', crm_industry:'Secteur',
    crm_stage:'Étape', crm_value:'Valeur', crm_prob:'Prob.',
    crm_drop:'Déposer ici', crm_win_prob:'Prob. succès',
    crm_no_deals:'Aucun deal. Créez votre premier deal.',
    crm_deal_value:'Valeur du deal',
    cli_sub:'{n} clients actifs · {mrr} MRR',
    cli_new:'Ajouter un contact', cli_all:'Tous les contacts',
    cli_no_clients:'Aucun client. Ajoutez votre premier client.',
    cli_mrr:'MRR', cli_lifetime:'Valeur totale', cli_active_proj:'Projets actifs',
    cli_health:'Santé', cli_since:'client depuis',
    cli_email:'E-mail', cli_call:'Appeler', cli_comm:'Historique de communication',
    cli_docs:'Documents', cli_contract:'Contrat', cli_active:'Actif',
    tasks_sub:'{n} tâches · {p} en attente',
    tasks_new:'Nouvelle tâche', tasks_no_tasks:'Aucune tâche. Ajoutez-en une pour commencer.',
    tasks_today:"Aujourd'hui", tasks_tomorrow:'Demain', tasks_week:'Cette semaine',
    tasks_all:'Toutes', tasks_pending:'En attente', tasks_done:'Terminées',
    proj_sub:'{n} tâches pour {c} clients',
    proj_new:'Nouvelle tâche', proj_drop:'Déposer ici',
    proj_filter:'Filtrer', proj_subtasks:'{a}/{b} sous-tâches',
    sup_sub:'{n} fournisseurs · {v} dépenses totales',
    sup_new:'Ajouter un fournisseur', sup_add_first:'Ajouter le premier',
    sup_no_sup:'Aucun fournisseur',
    sup_no_sub:'Ajoutez vos fournisseurs pour suivre les dépenses et coordonnées.',
    sup_cat:'Catégorie', sup_loc:'Lieu', sup_rating:'Note',
    sup_status:'Statut', sup_spend:'Dépenses', sup_all:'Tous les fournisseurs',
    sup_total:'Total fournisseurs', sup_total_spend:'Dépenses totales', sup_avg_rating:'Note moyenne',
    sup_preferred:'préférés', sup_of5:'sur 5',
    fin_sub:'Revenus, dépenses et trésorerie.',
    fin_overview:"Vue d'ensemble", fin_entries:'Toutes les entrées', fin_new:'Nouvelle entrée',
    fin_no_data:'Aucune donnée financière',
    fin_no_sub:'Ajoutez des factures et dépenses pour suivre vos revenus, coûts et bénéfices.',
    fin_add_first:'Ajouter la première entrée',
    fin_rev:'Revenus encaissés', fin_exp:'Total dépenses',
    fin_net:'Bénéfice net', fin_pending_inv:'Factures en attente',
    fin_rev_break:'Répartition des revenus', fin_summary:'Résumé',
    fin_recent:'Entrées récentes',
    fin_label:'Libellé', fin_type:'Type', fin_client:'Client',
    fin_date:'Date', fin_status:'Statut', fin_amount:'Montant',
    fin_invoice:'Facture', fin_expense:'Dépense',
    fin_paid:'Payée', fin_sent:'Envoyée', fin_draft:'Brouillon', fin_overdue:'En retard',
    fin_no_entries:'Aucune entrée. Ajoutez des factures et dépenses.',
    fin_total_inv:'Total facturé', fin_collected:'Encaissé',
    fin_still_pending:'Encore à encaisser', fin_expenses:'Dépenses',
    fin_net_profit:'Bénéfice net', fin_positive:'Positif', fin_negative:'Négatif',
    fin_invoices:'{n} factures payées', fin_entries_n:'{n} entrées',
    doc_sub:'{n} fichier{s} · contrats, devis, factures et plus.',
    doc_new:'Ajouter un document', doc_search:'Rechercher des documents',
    doc_no_docs:'Aucun document. Ajoutez votre premier fichier.',
    doc_all:'Tous les fichiers', doc_name:'Nom', doc_folder:'Dossier',
    doc_size:'Taille', doc_modified:'Modifié',
    doc_contracts:'Contrats', doc_quotes:'Devis', doc_invoices:'Factures',
    doc_certificates:'Certificats', doc_legal:'Juridique', doc_brand:'Identité de marque',
    pros_sub:'Campagnes de prospection et suivi des prospects.',
    pros_new_camp:'Nouvelle campagne', pros_new:'Nouveau prospect',
    pros_campaigns:'Campagnes', pros_prospects:'Prospects',
    pros_city:'Ville', pros_stage:'Étape', pros_last:'Dernier contact', pros_actions:'Actions',
    pros_no_camp:'Aucune campagne.', pros_no_pros:'Aucun prospect.',
    pros_emails:'E-mails envoyés', pros_open:"Taux d'ouverture", pros_reply:'Taux de réponse',
    pros_meetings:'RDV obtenus', pros_this_month:'ce mois',
    pros_active:'Active', pros_paused:'En pause',
    pros_across:'{n} campagnes', pros_opened:'{n} ouverts',
    pros_replies:'{n} réponses', pros_sent:'envoyés',
    pros_ai:'Générer un message IA', pros_ai_draft:'Brouillon IA',
    pros_for:'Personnalisé pour',
    pros_website:'Site web', pros_email:'E-mail', pros_phone:'Téléphone',
    pros_linkedin:'LinkedIn', pros_industry:'Secteur',
    ai_title:'Assistant IA',
    ai_sub:'Rédigez des e-mails et propositions, générez des scripts, analysez des leads et plus.',
    ai_ph:"Posez une question à l'assistant…",
    ai_p1:'Rédiger un e-mail de suivi', ai_p2:'Rédiger une proposition de projet',
    ai_p3:'Générer un script de vente', ai_p4:'Idées de campagne',
    ai_regen:'Régénérer', ai_send_email:"Envoyer l'e-mail",
    auto_title:'Automatisation',
    auto_sub:'Construisez des workflows qui automatisent vos tâches répétitives.',
    auto_coming:'Bientôt disponible',
    auto_desc:"Les workflows d'automatisation vous permettront de déclencher des actions automatiquement.",
    auto_dev:'Cette fonctionnalité est en cours de développement.',
    set_sub:'Espace de travail, facturation et intégrations.',
    set_workspace:'Espace de travail', set_ws_name:"Nom de l'espace", set_ws_shown:"Affiché dans toute l'app",
    set_account:'Compte', set_plan:'Abonnement', set_free:'Gratuit',
    set_integrations:'Intégrations', set_connected:'Connecté', set_connect:'Connecter',
    set_language:'Langue', set_lang_sub:"Langue de l'interface",
    set_tip:'Astuce : utilisez le panneau', set_tweaks:'Tweaks', set_tip2:'(en bas à droite) pour changer la mise en page.',
    set_lang_en:'English', set_lang_fr:'Français',
    m_new_client:'Nouveau contact', m_new_deal:'Nouveau deal', m_new_task:'Nouvelle tâche',
    m_new_proj:'Nouvelle tâche projet', m_new_prospect:'Nouveau prospect',
    m_new_campaign:'Nouvelle campagne', m_new_finance:'Nouvelle entrée',
    m_finance_sub:'Facture ou dépense',
    m_new_supplier:'Nouveau fournisseur', m_new_doc:'Ajouter un document',
    f_company:'Nom de la société', f_contact:'Nom du contact', f_industry:'Secteur',
    f_email:'E-mail', f_phone:'Téléphone', f_website:'Site web', f_mrr:'MRR (€)',
    f_health:'Santé', f_since:'Client depuis',
    f_value:'Valeur (€)', f_stage:'Étape', f_owner:'Responsable',
    f_title:'Titre', f_client:'Client', f_prio:'Priorité', f_due:'Échéance',
    f_col:'Colonne', f_due_date:"Date d'échéance", f_tags:'Tags (séparés par des virgules)',
    f_city:'Ville', f_linkedin:'LinkedIn', f_active:"Lancer comme active", f_campaign:'Nom de la campagne',
    f_type:'Type', f_amount:'Montant (€)', f_label:'Libellé', f_status:'Statut', f_date:'Date',
    f_category:'Catégorie', f_location:'Lieu',
    f_rating:'Note (0–5)', f_spend:'Dépenses annuelles (€)', f_size:'Taille',
    f_folder:'Dossier', f_filename:'Nom du fichier',
    f_health_good:'Bonne', f_health_watch:'Surveillance', f_health_risk:'À risque',
    stage_new_lead:'Nouveau lead', stage_qualified:'Qualifié', stage_proposal:'Devis envoyé',
    stage_negotiation:'Négociation', stage_won:'Gagné', stage_lost:'Perdu',
    stage_queued:'En file', stage_contacted:'Contacté', stage_replied:'Répondu',
    stage_meeting:'RDV obtenu', stage_converted:'Converti', stage_archived:'Archivé',
    ai_setup_title:"Configurer l'assistant IA", ai_setup_desc:"Ajoutez votre clé API Groq gratuite pour activer les actions IA.",
    ai_setup_step1:'Allez sur console.groq.com et créez un compte (gratuit, sans carte)',
    ai_setup_step2:'Cliquez "Create API Key" et copiez la clé',
    ai_setup_step3:'Collez-la ci-dessous et cliquez Activer',
    ai_activate:"Activer l'IA",
    inbox_add_account:'Ajouter une boîte mail', inbox_accounts:'Boîtes connectées',
    inbox_connect_email_ph:'votre@email.com', inbox_connect_email_label:'Votre adresse e-mail',
    f_prio_high:'Haute', f_prio_med:'Moyenne', f_prio_low:'Basse',
    f_today:"Aujourd'hui", f_tomorrow:'Demain', f_week:'Cette semaine',
    f_todo:'À faire', f_inprog:'En cours', f_waiting:'En attente', f_done:'Terminé',
    f_active:'Actif', f_paused:'En pause', f_preferred:'Préféré', f_trial:'Essai', f_inactive:'Inactif',
    f_inv:'Facture', f_exp:'Dépense', f_draft2:'Brouillon', f_sent:'Envoyée', f_paid:'Payée',
    doc_file_label:'Fichier (facultatif)', doc_file_ph:'Cliquer pour sélectionner un fichier…',
    doc_storage_note:'Nécessite un bucket "documents" dans Supabase Storage.',
    doc_uploading:'Envoi en cours…', doc_upload_err:"Échec de l'envoi — métadonnées enregistrées uniquement.",
    jobs_sub:'{n} candidatures', jobs_new:'Nouvelle candidature',
    jobs_total:'Total envoyées', jobs_pending:'En attente', jobs_no_reply:'sans réponse',
    jobs_interviews:'Entretiens', jobs_offers:'Offres', jobs_rate:'Taux de réponse', jobs_response_rate:'ont répondu',
    jobs_empty_title:'Aucune candidature', jobs_empty_desc:'Commencez à ajouter vos candidatures pour suivre où vous avez postulé.',
    jobs_no_match:'Aucun résultat', jobs_no_match_desc:'Aucune candidature ne correspond à ce filtre.',
    jobs_col_company:'Entreprise', jobs_col_position:'Poste', jobs_col_location:'Lieu',
    jobs_col_platform:'Plateforme', jobs_col_date:'Date', jobs_col_salary:'Salaire', jobs_col_status:'Statut',
    jobs_salary_min:'Salaire min (€)', jobs_salary_max:'Salaire max (€)',
    jobs_url:"Lien vers l'offre", jobs_contact:'Contact RH', jobs_notes:'Notes',
    jobs_view_offer:"Voir l'offre", jobs_search:'Rechercher…',
    job_applied:'Envoyée', job_interview:'Entretien', job_test:'Test technique',
    job_offer:'Offre reçue', job_rejected:'Refusé', job_withdrawn:'Retiré', job_accepted:'Accepté',
    inbox_title:'Boîte de réception', inbox_sub:'Tous vos e-mails, au même endroit.',
    inbox_connect:'Connectez votre boîte mail', inbox_connect_sub:'Synchronisez votre e-mail pour voir vos conversations.',
    inbox_connect_btn:'Connecter', inbox_imap_desc:'Tout fournisseur e-mail',
    inbox_privacy_title:'Vos e-mails restent sécurisés', inbox_privacy_desc:"Nous lisons vos e-mails uniquement à votre demande.",
    inbox_disconnect:'Déconnecter', inbox_compose:'Rédiger',
    inbox_sync_coming:'Synchronisation temps réel bientôt disponible', inbox_sync_desc:'Aperçu de votre boîte mail.',
    inbox_folder_inbox:'Boîte de réception', inbox_folder_sent:'Envoyés', inbox_folder_drafts:'Brouillons', inbox_folder_trash:'Corbeille',
    inbox_empty:'Ce dossier est vide.', inbox_from:'De', inbox_reply:'Répondre', inbox_no_selection:'Sélectionnez un e-mail pour le lire.',
    ai_no_key:"Pas de clé API configurée. Configurez-la sur cette page.",
    ai_tool_client:'Ajout client', ai_tool_deal:'Création deal', ai_tool_task:'Création tâche',
    ai_tool_prospect:'Ajout prospect', ai_tool_search:'Recherche web', ai_tool_data:'Lecture données',
    ai_clear:'Nouvelle conversation',
    set_ai:'Assistant IA (Groq — gratuit)', set_ai_key:'Clé API Groq (gratuit)', set_ai_key_ph:'gsk_…',
    set_ai_key_desc:'Clé gratuite sur console.groq.com — pas de carte bancaire requise.',
    set_ai_key_note:'Quota gratuit : 14 400 requêtes/jour. Stockée uniquement dans votre navigateur.',
    auth_login:'Se connecter', auth_register:'Créer un compte',
    auth_email:'Adresse e-mail', auth_password:'Mot de passe',
    auth_name:'Nom complet', auth_workspace:"Nom de l'espace de travail",
    auth_workspace_ph:'Mon Agence',
    auth_have:'Déjà un compte ?', auth_no_acc:'Pas encore de compte ?',
    auth_signin:'Se connecter', auth_create:'En créer un',
    auth_success:'Compte créé ! Connexion en cours…',
  }
};

export const LangCtx = createContext({ lang: 'en', setLang: () => {} });

export function useT() {
  const ctx = useContext(LangCtx);
  const lang = ctx?.lang || 'en';
  return (key, vars) => {
    let val = TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS.en[key] ?? key;
    if (vars) Object.entries(vars).forEach(([k, v]) => { val = String(val).replace('{' + k + '}', v); });
    return val;
  };
}

export function useLang() {
  return useContext(LangCtx);
}
